name: Playwright Tests
on:
  push:
    branches: [test-reporter]

jobs:
  run-playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.0.0"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        # Install only Chromium
        run: npx playwright install chromium --with-deps
      - name: Run Playwright tests
        run: npm run test:all
        continue-on-error: true

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Playwright Tests Reports
          path: "**/test-results.xml"
          reporter: java-junit

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
